# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/CES/project_2/project_2.cache/wt [current_project]
set_property parent.project_path H:/CES/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files H:/CES/project_2/project_2.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_rst_processing_system7_0_100M_0/design_2_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_rst_processing_system7_0_100M_0/design_2_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_rst_processing_system7_0_100M_0/design_2_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_0/design_2_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_0/design_2_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_0/design_2_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/CES/project_2/project_2.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all H:/CES/project_2/project_2.srcs/sources_1/bd/design_2/design_2_ooc.xdc]
set_property is_locked true [get_files H:/CES/project_2/project_2.srcs/sources_1/bd/design_2/design_2.bd]

read_vhdl -library xil_defaultlib H:/CES/project_2/project_2.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_2_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_2_wrapper.dcp

catch { report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb }
