# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/omid/documents/github/kes-ams/kes/lab3/a1_btn_read/a1_btn_read.tmp/lab3_a1_btn_ip_v1_0_project/lab3_a1_btn_ip_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/omid/documents/github/kes-ams/kes/lab3/a1_btn_read/a1_btn_read.tmp/lab3_a1_btn_ip_v1_0_project/lab3_a1_btn_ip_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/omid/Documents/GitHub/KES-AMS/KES/Lab3/ip_repo/lab3_a1_btn_ip_1.0 [current_project]
read_vhdl -library xil_defaultlib {
  c:/Users/omid/Documents/GitHub/KES-AMS/KES/Lab3/ip_repo/lab3_a1_btn_ip_1.0/hdl/lab3_a1_btn_ip_v1_0_S00_AXI.vhd
  c:/Users/omid/Documents/GitHub/KES-AMS/KES/Lab3/ip_repo/lab3_a1_btn_ip_1.0/hdl/lab3_a1_btn_ip_v1_0.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top lab3_a1_btn_ip_v1_0 -part xc7z020clg484-1


write_checkpoint -force -noxdef lab3_a1_btn_ip_v1_0.dcp

catch { report_utilization -file lab3_a1_btn_ip_v1_0_utilization_synth.rpt -pb lab3_a1_btn_ip_v1_0_utilization_synth.pb }
